### ISSUE TITLE
Failed releases still (sometimes) show as passed

### ISSUE THREAD

**Issue by jhollinger** [procore-oss/blueprinter-activerecord#5]
An early build was missing the TOTP code, but the build still returned as green. Not sure if the bug is in our actions or in the `gem` command itself.

[Example](https://github.com/procore-oss/blueprinter-activerecord/actions/runs/7849874085/job/21424133667#step:8:19)

Fix to get past it was change `MFA Level` in https://rubygems.org/settings/edit from `UI and API (recommended)` to `UI and gem signin` to allow automated pushes without MFA.

**Comment by jmeridth** [comment]
Related https://github.com/fac/ruby-gem-push-action/issues/15
